# -*- coding: utf-8 -*-

Chain_Attr_Info = {
    u'门禁抓拍': {'name': 'FaceGuardDt_DL', 'func': ''},
    u'口罩告警': {'name': 'MaskAlarm', 'func': ''},
    u'定时抓拍间隔': {'name': 'FaceTimedCapture', 'func': ''},
    u'定时抓拍间隔范围(s)': {'name': 'FaceTimedCaptureRange', 'func': 'proc_min_max'},
    u'定时抓拍重复次数': {'name': 'CaptureRepeatTimes', 'func': 'proc_min_max'},
    u'单个目标抓拍张数上限': {'name': 'SingPicNumLimit', 'func': 'proc_SingPicNumLimit'},
    u'目标整体抠图大小限制': {'name': 'BodySizeResitrict', 'func': ''},
    u'目标整体分开发送': {'name': 'SepratePanorama', 'func': ''},
    u'目标高级参数过滤': {'name': 'FaceAndMixAlgorAdvanceFilter', 'func': ''},
    u'是否支持FACEAPP': {'name': 'FACE_APP', 'func': ''},
    u'精简人脸识别': {'name': 'FewMMZFaceRecType', 'func': ''},
    u'目标库创建': {'name': 'ImportLib', 'func': ''},
    u'目标库导入': {'name': 'ImportPic', 'func': ''},
    u'人脸库容量(张数)': {'name': 'FacePicMaxNum', 'func': 'proc_num'},
    u'人脸库图片上限(KB)': {'name': 'LibPicFileSize', 'func': 'proc_size'},
    u'1拖N下人脸识别': {'name': 'YTNSupportFaceRecg', 'func': ''},
    u'1拖N下关闭后算法模式': {'name': 'DisableYTNDefaultAlgMode', 'func': ''},
    u'人脸库包导入上限(MB)': {'name': 'FaceZipPackageSize', 'func': 'proc_size'},
    u'人脸库图片建议大小(KB)': {'name': 'FaceImageSuggestedSize', 'func': 'proc_size'},
    # u'人脸库数量': {'name': '', 'func': ''},
    # u'白名单匹配告警': {'name': '', 'func': ''},
    # u'白名单未匹配告警': {'name': '', 'func': ''},
    # u'黑名单匹配告警': {'name': '', 'func': ''},
    u'热度图-是否支持使用头肩算法': {'name': 'HotMapSupportHS', 'func': ''},
    u'区域人数统计告警人数上限': {'name': 'CrowdDensityThreshold', 'func': ''},
    u'人群态势-是否支持使用头肩算法': {'name': 'HumanCountUseAlg', 'func': ''},
    u'红外人脸属性': {'name': 'InfFaceAttr', 'func': ''},
    u'红外人体属性': {'name': 'InfBodyAttr', 'func': ''},
    u'红外人体属性库': {'name': 'UseInfAttrLib', 'func': ''},
    u'车辆属性': {'name': 'VehAttr', 'func': ''},
    # u'车道总数': {'name': '', 'func': ''},
    u'目标画框': {'name': 'TargetDrawRect', 'func': ''},
    u'车辆事件检测': {'name': 'TrafficEvent', 'func': ''},
    u'人群态势分析': {'name': 'BehaviorAnalysis', 'func': ''},
    # u'轻智能行为分析(周界)检测': {'name': '', 'func': ''},
    u'复杂行为分析': {'name': 'HBA', 'func': ''},
    u'行为分析(周界)检测': {'name': 'BEH', 'func': ''},
    u'最大目标数': {'name': 'MaxObjs', 'func': 'proc_num'},
    u'平均目标数': {'name': 'AvergObjs', 'func': 'proc_num'},
    u'平均限流数': {'name': 'ScaleVale', 'func': 'proc_num'},
    u'红外骑行人属性': {'name': 'InfRiderAttr', 'func': ''},
    u'红外车辆属性': {'name': 'InfVehAttr', 'func': ''},
}

Intell_Info = {
    u'机非人同时检测目标数': {'name': 'MaxTrackNum_Face', 'func': 'proc_num'},
    u'人脸检测目标个数': {'name': 'MaxTrackNum_Vhd', 'func': 'proc_num'},
    u'1拖N支持最大智能能力': {'name': 'ITGT_SUPPORT_MODE_LIST', 'func': 'proc_ITGT_SUPPORT_MODE_LIST'},
}

ITGT_SUPPORT_MODE_LIST = {
    '0': u'不支持智能',
    '1': u'2路人脸',
    '2': u'2路机非人',
    '3': u'1路人脸+1路机非人',
    '4': u'3路人脸',
    '5': u'3路机非人',
    '6': u'1路人脸+2路机非人',
    '7': u'2路人脸+1路机非人',
    '8': u'5路人脸',
    '9': u'2路人脸+2路机非人',
    '10': u'4路机非人',
    '11': u'2路混行',
    '12': u'1路混行+2路人脸',
    '13': u'1路混行+2路机非人',
    '14': u'1路混行+1路人脸+1路机非人',
    '15': u'5路机非人',
    '16': u'1路人脸+4路机非人',
    '17': u'2路人脸+3路机非人',
    '18': u'3路人脸+2路机非人',
    '19': u'4路人脸+1路机非人',
}

YTN_Info = {
    u'主从分辨率之和(W)': {'name': 'YTNInfo', 'func': 'procYTNInfo'},
}
